# Generated by Django 2.0.5 on 2018-08-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_file', models.ImageField(blank=None, upload_to='images/')),
                ('p_uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=150)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('files', models.FileField(blank=True, upload_to='files/')),
                ('images', models.ImageField(blank=True, height_field='img_height', upload_to='images/', width_field='img_width')),
                ('img_height', models.PositiveIntegerField(default=600)),
                ('img_width', models.PositiveIntegerField(default=300)),
            ],
        ),
    ]
