# Generated by Django 2.0.5 on 2018-08-23 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180817_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_images',
            name='fk_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='feature_images',
            field=models.IntegerField(default=1),
        ),
    ]
