# Generated by Django 2.0.5 on 2018-08-23 05:53

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180823_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_images',
            name='fk_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='feature_images',
            field=models.IntegerField(default=builtins.id),
        ),
    ]
