# Generated by Django 2.0.5 on 2018-08-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180823_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_images',
            name='fk_post',
        ),
    ]
