# Generated by Django 2.0.5 on 2018-08-24 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_p_images_fk_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_images',
            name='fk_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
        ),
    ]
